<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipioSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('municipio')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        $municipios = [
            // ── 1. Amazonas ──────────────────────────────
            [1, 'Leticia'],
            [1, 'Puerto Nariño'],

            // ── 2. Antioquia ─────────────────────────────
            [2, 'Medellín'],
            [2, 'Abejorral'],
            [2, 'Abriaquí'],
            [2, 'Alejandría'],
            [2, 'Amagá'],
            [2, 'Amalfi'],
            [2, 'Andes'],
            [2, 'Angelópolis'],
            [2, 'Angostura'],
            [2, 'Anorí'],
            [2, 'Anzá'],
            [2, 'Apartadó'],
            [2, 'Arboletes'],
            [2, 'Argelia'],
            [2, 'Armenia'],
            [2, 'Barbosa'],
            [2, 'Bello'],
            [2, 'Betania'],
            [2, 'Betulia'],
            [2, 'Briceño'],
            [2, 'Buriticá'],
            [2, 'Cáceres'],
            [2, 'Caicedo'],
            [2, 'Caldas'],
            [2, 'Campamento'],
            [2, 'Cañasgordas'],
            [2, 'Caracolí'],
            [2, 'Caramanta'],
            [2, 'Carepa'],
            [2, 'Carolina del Príncipe'],
            [2, 'Caucasia'],
            [2, 'Chigorodó'],
            [2, 'Cisneros'],
            [2, 'Ciudad Bolívar'],
            [2, 'Cocorná'],
            [2, 'Concepción'],
            [2, 'Concordia'],
            [2, 'Copacabana'],
            [2, 'Dabeiba'],
            [2, 'Don Matías'],
            [2, 'Ebéjico'],
            [2, 'El Bagre'],
            [2, 'El Carmen de Viboral'],
            [2, 'El Santuario'],
            [2, 'Entrerríos'],
            [2, 'Envigado'],
            [2, 'Fredonia'],
            [2, 'Frontino'],
            [2, 'Giraldo'],
            [2, 'Girardota'],
            [2, 'Gómez Plata'],
            [2, 'Granada'],
            [2, 'Guadalupe'],
            [2, 'Guarne'],
            [2, 'Guatapé'],
            [2, 'Heliconia'],
            [2, 'Hispania'],
            [2, 'Itagüí'],
            [2, 'Ituango'],
            [2, 'Jardín'],
            [2, 'Jericó'],
            [2, 'La Ceja del Tambo'],
            [2, 'La Estrella'],
            [2, 'La Pintada'],
            [2, 'La Unión'],
            [2, 'Liborina'],
            [2, 'Maceo'],
            [2, 'Marinilla'],
            [2, 'Montebello'],
            [2, 'Murindó'],
            [2, 'Mutatá'],
            [2, 'Nariño'],
            [2, 'Necoclí'],
            [2, 'Nechí'],
            [2, 'Olaya'],
            [2, 'Peñol'],
            [2, 'Peque'],
            [2, 'Pueblorrico'],
            [2, 'Puerto Berrío'],
            [2, 'Puerto Nare'],
            [2, 'Puerto Triunfo'],
            [2, 'Remedios'],
            [2, 'Retiro'],
            [2, 'Rionegro'],
            [2, 'Sabanalarga'],
            [2, 'Sabaneta'],
            [2, 'Salgar'],
            [2, 'San Andrés de Cuerquia'],
            [2, 'San Carlos'],
            [2, 'San Francisco'],
            [2, 'San Jerónimo'],
            [2, 'San José de la Montaña'],
            [2, 'San Juan de Urabá'],
            [2, 'San Luis'],
            [2, 'San Pedro de los Milagros'],
            [2, 'San Pedro de Urabá'],
            [2, 'San Rafael'],
            [2, 'San Roque'],
            [2, 'San Vicente Ferrer'],
            [2, 'Santa Bárbara'],
            [2, 'Santa Rosa de Osos'],
            [2, 'Santo Domingo'],
            [2, 'Segovia'],
            [2, 'Sonsón'],
            [2, 'Sopetrán'],
            [2, 'Támesis'],
            [2, 'Tarazá'],
            [2, 'Tarso'],
            [2, 'Titiribí'],
            [2, 'Toledo'],
            [2, 'Turbo'],
            [2, 'Uramita'],
            [2, 'Urrao'],
            [2, 'Valdivia'],
            [2, 'Valparaíso'],
            [2, 'Vegachí'],
            [2, 'Venecia'],
            [2, 'Vigía del Fuerte'],
            [2, 'Yalí'],
            [2, 'Yarumal'],
            [2, 'Yolombó'],
            [2, 'Yondó'],
            [2, 'Zaragoza'],

            // ── 3. Arauca ────────────────────────────────
            [3, 'Arauca'],
            [3, 'Arauquita'],
            [3, 'Cravo Norte'],
            [3, 'Fortul'],
            [3, 'Puerto Rondón'],
            [3, 'Saravena'],
            [3, 'Tame'],

            // ── 4. Atlántico ─────────────────────────────
            [4, 'Barranquilla'],
            [4, 'Baranoa'],
            [4, 'Campo de la Cruz'],
            [4, 'Candelaria'],
            [4, 'Galapa'],
            [4, 'Juan de Acosta'],
            [4, 'Luruaco'],
            [4, 'Malambo'],
            [4, 'Manatí'],
            [4, 'Palmar de Varela'],
            [4, 'Piojó'],
            [4, 'Polonuevo'],
            [4, 'Ponedera'],
            [4, 'Puerto Colombia'],
            [4, 'Repelón'],
            [4, 'Sabanagrande'],
            [4, 'Sabanalarga'],
            [4, 'Santa Lucía'],
            [4, 'Santo Tomás'],
            [4, 'Soledad'],
            [4, 'Suán'],
            [4, 'Tubará'],
            [4, 'Usiacurí'],

            // ── 5. Bogotá D.C. ───────────────────────────
            [5, 'Bogotá D.C.'],

            // ── 6. Bolívar ───────────────────────────────
            [6, 'Cartagena'],
            [6, 'Achí'],
            [6, 'Altos del Rosario'],
            [6, 'Arenal'],
            [6, 'Arjona'],
            [6, 'Arroyohondo'],
            [6, 'Barranco de Loba'],
            [6, 'Calamar'],
            [6, 'Cantagallo'],
            [6, 'Cicuco'],
            [6, 'Clemencia'],
            [6, 'Córdoba'],
            [6, 'El Carmen de Bolívar'],
            [6, 'El Guamo'],
            [6, 'El Peñón'],
            [6, 'Hatillo de Loba'],
            [6, 'Magangué'],
            [6, 'Mahates'],
            [6, 'Margarita'],
            [6, 'María la Baja'],
            [6, 'Mompox'],
            [6, 'Montecristo'],
            [6, 'Morales'],
            [6, 'Norosí'],
            [6, 'Pinillos'],
            [6, 'Regidor'],
            [6, 'Río Viejo'],
            [6, 'San Cristóbal'],
            [6, 'San Estanislao'],
            [6, 'San Fernando'],
            [6, 'San Jacinto'],
            [6, 'San Jacinto del Cauca'],
            [6, 'San Juan Nepomuceno'],
            [6, 'San Martín de Loba'],
            [6, 'San Pablo'],
            [6, 'Santa Catalina'],
            [6, 'Santa Rosa'],
            [6, 'Santa Rosa del Sur'],
            [6, 'Simití'],
            [6, 'Soplaviento'],
            [6, 'Talaigua Nuevo'],
            [6, 'Tiquisio'],
            [6, 'Turbaco'],
            [6, 'Turbaná'],
            [6, 'Villanueva'],
            [6, 'Zambrano'],

            // ── 7. Boyacá ────────────────────────────────
            [7, 'Tunja'],
            [7, 'Almeida'],
            [7, 'Aquitania'],
            [7, 'Arcabuco'],
            [7, 'Belén'],
            [7, 'Berbeo'],
            [7, 'Betéitiva'],
            [7, 'Boavita'],
            [7, 'Boyacá'],
            [7, 'Briceño'],
            [7, 'Buenavista'],
            [7, 'Busbanzá'],
            [7, 'Caldas'],
            [7, 'Campohermoso'],
            [7, 'Cerinza'],
            [7, 'Chinavita'],
            [7, 'Chiquinquirá'],
            [7, 'Chíquiza'],
            [7, 'Chiscas'],
            [7, 'Chita'],
            [7, 'Chitaraque'],
            [7, 'Chivatá'],
            [7, 'Chivor'],
            [7, 'Ciénega'],
            [7, 'Cómbita'],
            [7, 'Coper'],
            [7, 'Corrales'],
            [7, 'Covarachía'],
            [7, 'Cubará'],
            [7, 'Cucaita'],
            [7, 'Cuítiva'],
            [7, 'Duitama'],
            [7, 'El Cocuy'],
            [7, 'El Espino'],
            [7, 'Firavitoba'],
            [7, 'Floresta'],
            [7, 'Gachantivá'],
            [7, 'Gámeza'],
            [7, 'Garagoa'],
            [7, 'Guacamayas'],
            [7, 'Guateque'],
            [7, 'Guayatá'],
            [7, 'Güicán de la Sierra'],
            [7, 'Iza'],
            [7, 'Jenesano'],
            [7, 'Jericó'],
            [7, 'La Capilla'],
            [7, 'La Uvita'],
            [7, 'La Victoria'],
            [7, 'Labranzagrande'],
            [7, 'Macanal'],
            [7, 'Maripí'],
            [7, 'Miraflores'],
            [7, 'Mongua'],
            [7, 'Monguí'],
            [7, 'Moniquirá'],
            [7, 'Motavita'],
            [7, 'Muzo'],
            [7, 'Nobsa'],
            [7, 'Nuevo Colón'],
            [7, 'Oicatá'],
            [7, 'Otanche'],
            [7, 'Pachavita'],
            [7, 'Páez'],
            [7, 'Paipa'],
            [7, 'Pajarito'],
            [7, 'Panqueba'],
            [7, 'Pauna'],
            [7, 'Paya'],
            [7, 'Paz de Río'],
            [7, 'Pesca'],
            [7, 'Pisba'],
            [7, 'Puerto Boyacá'],
            [7, 'Quípama'],
            [7, 'Ramiriquí'],
            [7, 'Ráquira'],
            [7, 'Rondón'],
            [7, 'Saboyá'],
            [7, 'Sáchica'],
            [7, 'Samacá'],
            [7, 'San Eduardo'],
            [7, 'San José de Pare'],
            [7, 'San Luis de Gaceno'],
            [7, 'San Mateo'],
            [7, 'San Miguel de Sema'],
            [7, 'San Pablo de Borbur'],
            [7, 'Santa María'],
            [7, 'Santa Rosa de Viterbo'],
            [7, 'Santa Sofía'],
            [7, 'Santana'],
            [7, 'Sativanorte'],
            [7, 'Sativasur'],
            [7, 'Siachoque'],
            [7, 'Soatá'],
            [7, 'Socha'],
            [7, 'Socotá'],
            [7, 'Soracá'],
            [7, 'Sotaquirá'],
            [7, 'Susacón'],
            [7, 'Sutamarchán'],
            [7, 'Sutatenza'],
            [7, 'Tasco'],
            [7, 'Tenza'],
            [7, 'Tibaná'],
            [7, 'Tibasosa'],
            [7, 'Tinjacá'],
            [7, 'Tipacoque'],
            [7, 'Toca'],
            [7, 'Togüí'],
            [7, 'Tópaga'],
            [7, 'Tota'],
            [7, 'Turmequé'],
            [7, 'Tuta'],
            [7, 'Tutazá'],
            [7, 'Umbita'],
            [7, 'Ventaquemada'],
            [7, 'Villa de Leyva'],
            [7, 'Viracachá'],
            [7, 'Zetaquira'],

            // ── 8. Caldas ────────────────────────────────
            [8, 'Manizales'],
            [8, 'Aguadas'],
            [8, 'Anserma'],
            [8, 'Aranzazu'],
            [8, 'Belalcázar'],
            [8, 'Chinchiná'],
            [8, 'Filadelfia'],
            [8, 'La Dorada'],
            [8, 'La Merced'],
            [8, 'Manzanares'],
            [8, 'Marmato'],
            [8, 'Marquetalia'],
            [8, 'Marulanda'],
            [8, 'Neira'],
            [8, 'Norcasia'],
            [8, 'Pácora'],
            [8, 'Palestina'],
            [8, 'Pensilvania'],
            [8, 'Riosucio'],
            [8, 'Risaralda'],
            [8, 'Salamina'],
            [8, 'Samaná'],
            [8, 'San José'],
            [8, 'Supía'],
            [8, 'Victoria'],
            [8, 'Villamaría'],
            [8, 'Viterbo'],

            // ── 9. Caquetá ───────────────────────────────
            [9, 'Florencia'],
            [9, 'Albania'],
            [9, 'Belén de los Andaquíes'],
            [9, 'Cartagena del Chairá'],
            [9, 'Curillo'],
            [9, 'El Doncello'],
            [9, 'El Paujil'],
            [9, 'La Montañita'],
            [9, 'Milán'],
            [9, 'Morelia'],
            [9, 'Puerto Rico'],
            [9, 'San José del Fragua'],
            [9, 'San Vicente del Caguán'],
            [9, 'Solano'],
            [9, 'Solita'],
            [9, 'Valparaíso'],

            // ── 10. Casanare ─────────────────────────────
            [10, 'Yopal'],
            [10, 'Aguazul'],
            [10, 'Chámeza'],
            [10, 'Hato Corozal'],
            [10, 'La Salina'],
            [10, 'Maní'],
            [10, 'Monterrey'],
            [10, 'Nunchía'],
            [10, 'Orocué'],
            [10, 'Paz de Ariporo'],
            [10, 'Pore'],
            [10, 'Recetor'],
            [10, 'Sabanalarga'],
            [10, 'Sácama'],
            [10, 'San Luis de Palenque'],
            [10, 'Támara'],
            [10, 'Tauramena'],
            [10, 'Trinidad'],
            [10, 'Villanueva'],

            // ── 11. Cauca ────────────────────────────────
            [11, 'Popayán'],
            [11, 'Almaguer'],
            [11, 'Argelia'],
            [11, 'Balboa'],
            [11, 'Bolívar'],
            [11, 'Buenos Aires'],
            [11, 'Cajibío'],
            [11, 'Caldono'],
            [11, 'Caloto'],
            [11, 'Corinto'],
            [11, 'El Tambo'],
            [11, 'Florencia'],
            [11, 'Guachené'],
            [11, 'Guapi'],
            [11, 'Inzá'],
            [11, 'Jambaló'],
            [11, 'La Sierra'],
            [11, 'La Vega'],
            [11, 'López de Micay'],
            [11, 'Mercaderes'],
            [11, 'Miranda'],
            [11, 'Morales'],
            [11, 'Padilla'],
            [11, 'Páez'],
            [11, 'Patía'],
            [11, 'Piamonte'],
            [11, 'Piendamó-Tunía'],
            [11, 'Puerto Tejada'],
            [11, 'Puracé'],
            [11, 'Rosas'],
            [11, 'San Sebastián'],
            [11, 'Santa Rosa'],
            [11, 'Santander de Quilichao'],
            [11, 'Silvia'],
            [11, 'Sotará Paispamba'],
            [11, 'Sucre'],
            [11, 'Suárez'],
            [11, 'Timbío'],
            [11, 'Timbiquí'],
            [11, 'Toribío'],
            [11, 'Totoró'],
            [11, 'Villa Rica'],

            // ── 12. Cesar ────────────────────────────────
            [12, 'Valledupar'],
            [12, 'Aguachica'],
            [12, 'Agustín Codazzi'],
            [12, 'Astrea'],
            [12, 'Becerril'],
            [12, 'Bosconia'],
            [12, 'Chimichagua'],
            [12, 'Chiriguaná'],
            [12, 'Curumaní'],
            [12, 'El Copey'],
            [12, 'El Paso'],
            [12, 'Gamarra'],
            [12, 'González'],
            [12, 'La Gloria'],
            [12, 'La Jagua de Ibirico'],
            [12, 'La Paz'],
            [12, 'Manaure'],
            [12, 'Pailitas'],
            [12, 'Pelaya'],
            [12, 'Pueblo Bello'],
            [12, 'Río de Oro'],
            [12, 'San Alberto'],
            [12, 'San Diego'],
            [12, 'San Martín'],
            [12, 'Tamalameque'],

            // ── 13. Chocó ────────────────────────────────
            [13, 'Quibdó'],
            [13, 'Acandí'],
            [13, 'Alto Baudó'],
            [13, 'Atrato'],
            [13, 'Bagadó'],
            [13, 'Bahía Solano'],
            [13, 'Bajo Baudó'],
            [13, 'Bojayá'],
            [13, 'Carmen del Darién'],
            [13, 'Cértegui'],
            [13, 'Condoto'],
            [13, 'El Carmen de Atrato'],
            [13, 'El Litoral del San Juan'],
            [13, 'Istmina'],
            [13, 'Juradó'],
            [13, 'Lloró'],
            [13, 'Medio Atrato'],
            [13, 'Medio Baudó'],
            [13, 'Medio San Juan'],
            [13, 'Nóvita'],
            [13, 'Nuquí'],
            [13, 'Río Iro'],
            [13, 'Río Quito'],
            [13, 'Riosucio'],
            [13, 'San José del Palmar'],
            [13, 'Sipí'],
            [13, 'Tadó'],
            [13, 'Unguía'],
            [13, 'Unión Panamericana'],

            // ── 14. Córdoba ──────────────────────────────
            [14, 'Montería'],
            [14, 'Ayapel'],
            [14, 'Buenavista'],
            [14, 'Canalete'],
            [14, 'Cereté'],
            [14, 'Chimá'],
            [14, 'Chinú'],
            [14, 'Ciénaga de Oro'],
            [14, 'Cotorra'],
            [14, 'La Apartada'],
            [14, 'Lorica'],
            [14, 'Los Córdobas'],
            [14, 'Momil'],
            [14, 'Montelíbano'],
            [14, 'Moñitos'],
            [14, 'Planeta Rica'],
            [14, 'Pueblo Nuevo'],
            [14, 'Puerto Escondido'],
            [14, 'Puerto Libertador'],
            [14, 'Purísima de la Concepción'],
            [14, 'Sahagún'],
            [14, 'San Andrés de Sotavento'],
            [14, 'San Antero'],
            [14, 'San Bernardo del Viento'],
            [14, 'San Carlos'],
            [14, 'San José de Uré'],
            [14, 'San Pelayo'],
            [14, 'Tierralta'],
            [14, 'Tuchín'],
            [14, 'Valencia'],

            // ── 15. Cundinamarca ─────────────────────────
            [15, 'Agua de Dios'],
            [15, 'Albán'],
            [15, 'Anapoima'],
            [15, 'Anolaima'],
            [15, 'Apulo'],
            [15, 'Arbeláez'],
            [15, 'Beltrán'],
            [15, 'Bituima'],
            [15, 'Bojacá'],
            [15, 'Cabrera'],
            [15, 'Cachipay'],
            [15, 'Cajicá'],
            [15, 'Caparrapí'],
            [15, 'Cáqueza'],
            [15, 'Carmen de Carupa'],
            [15, 'Chaguaní'],
            [15, 'Chía'],
            [15, 'Chipaque'],
            [15, 'Choachí'],
            [15, 'Chocontá'],
            [15, 'Cogua'],
            [15, 'Cota'],
            [15, 'Cucunubá'],
            [15, 'El Colegio'],
            [15, 'El Peñón'],
            [15, 'El Rosal'],
            [15, 'Facatativá'],
            [15, 'Fomeque'],
            [15, 'Fosca'],
            [15, 'Funza'],
            [15, 'Fúquene'],
            [15, 'Fusagasugá'],
            [15, 'Gachalá'],
            [15, 'Gachancipá'],
            [15, 'Gachetá'],
            [15, 'Gama'],
            [15, 'Girardot'],
            [15, 'Granada'],
            [15, 'Guachetá'],
            [15, 'Guaduas'],
            [15, 'Guasca'],
            [15, 'Guataquí'],
            [15, 'Guatavita'],
            [15, 'Guayabetal'],
            [15, 'Gutiérrez'],
            [15, 'Jerusalén'],
            [15, 'Junín'],
            [15, 'La Calera'],
            [15, 'La Mesa'],
            [15, 'La Palma'],
            [15, 'La Peña'],
            [15, 'La Vega'],
            [15, 'Lenguazaque'],
            [15, 'Machetá'],
            [15, 'Madrid'],
            [15, 'Manta'],
            [15, 'Medina'],
            [15, 'Mosquera'],
            [15, 'Nariño'],
            [15, 'Nemocón'],
            [15, 'Nilo'],
            [15, 'Nimaima'],
            [15, 'Nocaima'],
            [15, 'Pacho'],
            [15, 'Paime'],
            [15, 'Pandi'],
            [15, 'Paratebueno'],
            [15, 'Pasca'],
            [15, 'Puerto Salgar'],
            [15, 'Pulí'],
            [15, 'Quebradanegra'],
            [15, 'Quetame'],
            [15, 'Quipile'],
            [15, 'Ricaurte'],
            [15, 'San Antonio del Tequendama'],
            [15, 'San Bernardo'],
            [15, 'San Cayetano'],
            [15, 'San Francisco'],
            [15, 'San Juan de Rioseco'],
            [15, 'Sasaima'],
            [15, 'Sesquilé'],
            [15, 'Sibaté'],
            [15, 'Silvania'],
            [15, 'Simijaca'],
            [15, 'Soacha'],
            [15, 'Sopó'],
            [15, 'Subachoque'],
            [15, 'Suesca'],
            [15, 'Supatá'],
            [15, 'Susa'],
            [15, 'Sutatausa'],
            [15, 'Tabio'],
            [15, 'Tausa'],
            [15, 'Tena'],
            [15, 'Tenjo'],
            [15, 'Tibacuy'],
            [15, 'Tibirita'],
            [15, 'Tocaima'],
            [15, 'Tocancipá'],
            [15, 'Topaipí'],
            [15, 'Ubalá'],
            [15, 'Ubaque'],
            [15, 'Ubaté'],
            [15, 'Une'],
            [15, 'Útica'],
            [15, 'Vergara'],
            [15, 'Vianí'],
            [15, 'Villagómez'],
            [15, 'Villapinzón'],
            [15, 'Villeta'],
            [15, 'Viotá'],
            [15, 'Yacopí'],
            [15, 'Zipacón'],
            [15, 'Zipaquirá'],

            // ── 16. Guainía ──────────────────────────────
            [16, 'Inírida'],
            [16, 'Barranco Minas'],
            [16, 'Cacahual'],
            [16, 'La Guadalupe'],
            [16, 'Mapiripana'],
            [16, 'Morichal Nuevo'],
            [16, 'Pana Pana'],
            [16, 'Puerto Colombia'],
            [16, 'San Felipe'],

            // ── 17. Guaviare ─────────────────────────────
            [17, 'San José del Guaviare'],
            [17, 'Calamar'],
            [17, 'El Retorno'],
            [17, 'Miraflores'],

            // ── 18. Huila ────────────────────────────────
            [18, 'Neiva'],
            [18, 'Acevedo'],
            [18, 'Agrado'],
            [18, 'Aipe'],
            [18, 'Algeciras'],
            [18, 'Altamira'],
            [18, 'Baraya'],
            [18, 'Campoalegre'],
            [18, 'Colombia'],
            [18, 'Elías'],
            [18, 'Garzón'],
            [18, 'Gigante'],
            [18, 'Guadalupe'],
            [18, 'Hobo'],
            [18, 'Iquira'],
            [18, 'Isnos'],
            [18, 'La Argentina'],
            [18, 'La Plata'],
            [18, 'Nataga'],
            [18, 'Oporapa'],
            [18, 'Paicol'],
            [18, 'Palermo'],
            [18, 'Palestina'],
            [18, 'Pital'],
            [18, 'Pitalito'],
            [18, 'Rivera'],
            [18, 'Saladoblanco'],
            [18, 'San Agustín'],
            [18, 'Santa María'],
            [18, 'Suaza'],
            [18, 'Tarqui'],
            [18, 'Tello'],
            [18, 'Teruel'],
            [18, 'Tesalia'],
            [18, 'Timaná'],
            [18, 'Villavieja'],
            [18, 'Yaguará'],

            // ── 19. La Guajira ───────────────────────────
            [19, 'Riohacha'],
            [19, 'Albania'],
            [19, 'Barrancas'],
            [19, 'Dibulla'],
            [19, 'Distracción'],
            [19, 'El Molino'],
            [19, 'Fonseca'],
            [19, 'Hatonuevo'],
            [19, 'La Jagua del Pilar'],
            [19, 'Maicao'],
            [19, 'Manaure'],
            [19, 'San Juan del Cesar'],
            [19, 'Uribia'],
            [19, 'Urumita'],
            [19, 'Villanueva'],

            // ── 20. Magdalena ────────────────────────────
            [20, 'Santa Marta'],
            [20, 'Algarrobo'],
            [20, 'Aracataca'],
            [20, 'Ariguaní'],
            [20, 'Cerro de San Antonio'],
            [20, 'Chivolo'],
            [20, 'Ciénaga'],
            [20, 'Concordia'],
            [20, 'El Banco'],
            [20, 'El Piñón'],
            [20, 'El Retén'],
            [20, 'Fundación'],
            [20, 'Guamal'],
            [20, 'Nueva Granada'],
            [20, 'Pedraza'],
            [20, 'Pijiño del Carmen'],
            [20, 'Pivijay'],
            [20, 'Plato'],
            [20, 'Puebloviejo'],
            [20, 'Remolino'],
            [20, 'Sabanas de San Ángel'],
            [20, 'Salamina'],
            [20, 'San Sebastián de Buenavista'],
            [20, 'San Zenón'],
            [20, 'Santa Ana'],
            [20, 'Santa Bárbara de Pinto'],
            [20, 'Sitionuevo'],
            [20, 'Tenerife'],
            [20, 'Zapayán'],
            [20, 'Zona Bananera'],

            // ── 21. Meta ─────────────────────────────────
            [21, 'Villavicencio'],
            [21, 'Acacías'],
            [21, 'Barranca de Upía'],
            [21, 'Cabuyaro'],
            [21, 'Castilla la Nueva'],
            [21, 'Cubarral'],
            [21, 'Cumaral'],
            [21, 'El Calvario'],
            [21, 'El Castillo'],
            [21, 'El Dorado'],
            [21, 'Fuente de Oro'],
            [21, 'Granada'],
            [21, 'Guamal'],
            [21, 'La Macarena'],
            [21, 'La Uribe'],
            [21, 'Lejanías'],
            [21, 'Mapiripán'],
            [21, 'Mesetas'],
            [21, 'Puerto Concordia'],
            [21, 'Puerto Gaitán'],
            [21, 'Puerto Lleras'],
            [21, 'Puerto López'],
            [21, 'Puerto Rico'],
            [21, 'Restrepo'],
            [21, 'San Carlos de Guaroa'],
            [21, 'San Juan de Arama'],
            [21, 'San Juanito'],
            [21, 'San Martín'],
            [21, 'Vistahermosa'],

            // ── 22. Nariño ───────────────────────────────
            [22, 'Pasto'],
            [22, 'Albán'],
            [22, 'Aldana'],
            [22, 'Ancuyá'],
            [22, 'Arboleda'],
            [22, 'Barbacoas'],
            [22, 'Belén'],
            [22, 'Buesaco'],
            [22, 'Chachagüí'],
            [22, 'Colón'],
            [22, 'Consacá'],
            [22, 'Contadero'],
            [22, 'Córdoba'],
            [22, 'Cuaspud Carlosama'],
            [22, 'Cumbal'],
            [22, 'Cumbitara'],
            [22, 'El Charco'],
            [22, 'El Peñol'],
            [22, 'El Rosario'],
            [22, 'El Tablón de Gómez'],
            [22, 'El Tambo'],
            [22, 'Francisco Pizarro'],
            [22, 'Funes'],
            [22, 'Guachucal'],
            [22, 'Guaitarilla'],
            [22, 'Gualmatán'],
            [22, 'Iles'],
            [22, 'Imués'],
            [22, 'Ipiales'],
            [22, 'La Cruz'],
            [22, 'La Florida'],
            [22, 'La Llanada'],
            [22, 'La Tola'],
            [22, 'La Unión'],
            [22, 'Leiva'],
            [22, 'Linares'],
            [22, 'Los Andes'],
            [22, 'Magüí Payán'],
            [22, 'Mallama'],
            [22, 'Mosquera'],
            [22, 'Nariño'],
            [22, 'Olaya Herrera'],
            [22, 'Ospina'],
            [22, 'Policarpa'],
            [22, 'Potosí'],
            [22, 'Providencia'],
            [22, 'Puerres'],
            [22, 'Pupiales'],
            [22, 'Ricaurte'],
            [22, 'Roberto Payán'],
            [22, 'Samaniego'],
            [22, 'San Bernardo'],
            [22, 'San Lorenzo'],
            [22, 'San Pablo'],
            [22, 'San Pedro de Cartago'],
            [22, 'Sandoná'],
            [22, 'Santa Bárbara'],
            [22, 'Santacruz'],
            [22, 'Sapuyes'],
            [22, 'Taminango'],
            [22, 'Tangua'],
            [22, 'Tumaco'],
            [22, 'Túquerres'],
            [22, 'Yacuanquer'],

            // ── 23. Norte de Santander ───────────────────
            [23, 'Cúcuta'],
            [23, 'Ábrego'],
            [23, 'Arboledas'],
            [23, 'Bochalema'],
            [23, 'Bucarasica'],
            [23, 'Cácota'],
            [23, 'Cáchira'],
            [23, 'Chinácota'],
            [23, 'Chitagá'],
            [23, 'Convención'],
            [23, 'Cucutilla'],
            [23, 'Durania'],
            [23, 'El Carmen'],
            [23, 'El Tarra'],
            [23, 'El Zulia'],
            [23, 'Gramalote'],
            [23, 'Hacarí'],
            [23, 'Herrán'],
            [23, 'La Esperanza'],
            [23, 'La Playa de Belén'],
            [23, 'Labateca'],
            [23, 'Los Patios'],
            [23, 'Lourdes'],
            [23, 'Mutiscua'],
            [23, 'Ocaña'],
            [23, 'Pamplona'],
            [23, 'Pamplonita'],
            [23, 'Puerto Santander'],
            [23, 'Ragonvalia'],
            [23, 'Salazar'],
            [23, 'San Calixto'],
            [23, 'San Cayetano'],
            [23, 'Santiago'],
            [23, 'Sardinata'],
            [23, 'Silos'],
            [23, 'Teorama'],
            [23, 'Tibú'],
            [23, 'Toledo'],
            [23, 'Villa Caro'],
            [23, 'Villa del Rosario'],

            // ── 24. Putumayo ─────────────────────────────
            [24, 'Mocoa'],
            [24, 'Colón'],
            [24, 'Orito'],
            [24, 'Puerto Asís'],
            [24, 'Puerto Caicedo'],
            [24, 'Puerto Guzmán'],
            [24, 'Puerto Leguízamo'],
            [24, 'San Francisco'],
            [24, 'San Miguel'],
            [24, 'Santiago'],
            [24, 'Sibundoy'],
            [24, 'Valle del Guamuez'],
            [24, 'Villagarzón'],

            // ── 25. Quindío ──────────────────────────────
            [25, 'Armenia'],
            [25, 'Buenavista'],
            [25, 'Calarcá'],
            [25, 'Circasia'],
            [25, 'Córdoba'],
            [25, 'Filandia'],
            [25, 'Génova'],
            [25, 'La Tebaida'],
            [25, 'Montenegro'],
            [25, 'Pijao'],
            [25, 'Quimbaya'],
            [25, 'Salento'],

            // ── 26. Risaralda ────────────────────────────
            [26, 'Pereira'],
            [26, 'Apía'],
            [26, 'Balboa'],
            [26, 'Belén de Umbría'],
            [26, 'Dosquebradas'],
            [26, 'Guática'],
            [26, 'La Celia'],
            [26, 'La Virginia'],
            [26, 'Marsella'],
            [26, 'Mistrató'],
            [26, 'Pueblo Rico'],
            [26, 'Quinchía'],
            [26, 'Santa Rosa de Cabal'],
            [26, 'Santuario'],

            // ── 27. San Andrés y Providencia ─────────────
            [27, 'San Andrés'],
            [27, 'Providencia y Santa Catalina'],

            // ── 28. Santander ────────────────────────────
            [28, 'Bucaramanga'],
            [28, 'Aguada'],
            [28, 'Albania'],
            [28, 'Aratoca'],
            [28, 'Barbosa'],
            [28, 'Barichara'],
            [28, 'Barrancabermeja'],
            [28, 'Betulia'],
            [28, 'Bolívar'],
            [28, 'Cabrera'],
            [28, 'California'],
            [28, 'Capitanejo'],
            [28, 'Carcasí'],
            [28, 'Cepitá'],
            [28, 'Cerrito'],
            [28, 'Charalá'],
            [28, 'Chima'],
            [28, 'Chipatá'],
            [28, 'Cimitarra'],
            [28, 'Concepción'],
            [28, 'Confines'],
            [28, 'Contratación'],
            [28, 'Coromoro'],
            [28, 'Curití'],
            [28, 'El Carmen de Chucurí'],
            [28, 'El Guacamayo'],
            [28, 'El Peñón'],
            [28, 'El Playón'],
            [28, 'Encino'],
            [28, 'Enciso'],
            [28, 'Florián'],
            [28, 'Floridablanca'],
            [28, 'Galán'],
            [28, 'Gámbita'],
            [28, 'Girón'],
            [28, 'Guaca'],
            [28, 'Guadalupe'],
            [28, 'Guapotá'],
            [28, 'Guavatá'],
            [28, 'Güepsa'],
            [28, 'Hato'],
            [28, 'Jesús María'],
            [28, 'Jordán'],
            [28, 'La Belleza'],
            [28, 'Landázuri'],
            [28, 'La Paz'],
            [28, 'Lebrija'],
            [28, 'Los Santos'],
            [28, 'Macaravita'],
            [28, 'Málaga'],
            [28, 'Matanza'],
            [28, 'Mogotes'],
            [28, 'Molagavita'],
            [28, 'Ocamonte'],
            [28, 'Oiba'],
            [28, 'Onzaga'],
            [28, 'Palmar'],
            [28, 'Palmas del Socorro'],
            [28, 'Páramo'],
            [28, 'Piedecuesta'],
            [28, 'Pinchote'],
            [28, 'Puente Nacional'],
            [28, 'Puerto Parra'],
            [28, 'Puerto Wilches'],
            [28, 'Rionegro'],
            [28, 'Sabana de Torres'],
            [28, 'San Andrés'],
            [28, 'San Benito'],
            [28, 'San Gil'],
            [28, 'San Joaquín'],
            [28, 'San José de Miranda'],
            [28, 'San Miguel'],
            [28, 'San Vicente de Chucurí'],
            [28, 'Santa Bárbara'],
            [28, 'Santa Helena del Opón'],
            [28, 'Simacota'],
            [28, 'Socorro'],
            [28, 'Suaita'],
            [28, 'Sucre'],
            [28, 'Suratá'],
            [28, 'Tona'],
            [28, 'Valle de San José'],
            [28, 'Vélez'],
            [28, 'Vetas'],
            [28, 'Villanueva'],
            [28, 'Zapatoca'],

            // ── 29. Sucre ────────────────────────────────
            [29, 'Sincelejo'],
            [29, 'Buenavista'],
            [29, 'Caimito'],
            [29, 'Chalán'],
            [29, 'Colosó'],
            [29, 'Corozal'],
            [29, 'Coveñas'],
            [29, 'El Roble'],
            [29, 'Galeras'],
            [29, 'Guaranda'],
            [29, 'La Unión'],
            [29, 'Los Palmitos'],
            [29, 'Majagual'],
            [29, 'Morroa'],
            [29, 'Ovejas'],
            [29, 'Palmito'],
            [29, 'Sampués'],
            [29, 'San Benito Abad'],
            [29, 'San Juan de Betulia'],
            [29, 'San Marcos'],
            [29, 'San Onofre'],
            [29, 'San Pedro'],
            [29, 'Santiago de Tolú'],
            [29, 'Sincé'],
            [29, 'Sucre'],
            [29, 'Tolú Viejo'],

            // ── 30. Tolima ───────────────────────────────
            [30, 'Ibagué'],
            [30, 'Alpujarra'],
            [30, 'Alvarado'],
            [30, 'Ambalema'],
            [30, 'Anzoátegui'],
            [30, 'Armero'],
            [30, 'Ataco'],
            [30, 'Cajamarca'],
            [30, 'Carmen de Apicalá'],
            [30, 'Casabianca'],
            [30, 'Chaparral'],
            [30, 'Coello'],
            [30, 'Coyaima'],
            [30, 'Cunday'],
            [30, 'Dolores'],
            [30, 'Espinal'],
            [30, 'Falan'],
            [30, 'Flandes'],
            [30, 'Fresno'],
            [30, 'Guamo'],
            [30, 'Herveo'],
            [30, 'Honda'],
            [30, 'Icononzo'],
            [30, 'Lérida'],
            [30, 'Líbano'],
            [30, 'Mariquita'],
            [30, 'Melgar'],
            [30, 'Murillo'],
            [30, 'Natagaima'],
            [30, 'Ortega'],
            [30, 'Palocabildo'],
            [30, 'Piedras'],
            [30, 'Planadas'],
            [30, 'Prado'],
            [30, 'Purificación'],
            [30, 'Rioblanco'],
            [30, 'Roncesvalles'],
            [30, 'Rovira'],
            [30, 'Saldaña'],
            [30, 'San Antonio'],
            [30, 'San Luis'],
            [30, 'Santa Isabel'],
            [30, 'Suárez'],
            [30, 'Valle de San Juan'],
            [30, 'Venadillo'],
            [30, 'Villahermosa'],
            [30, 'Villarrica'],

            // ── 31. Valle del Cauca ──────────────────────
            [31, 'Cali'],
            [31, 'Alcalá'],
            [31, 'Andalucía'],
            [31, 'Ansermanuevo'],
            [31, 'Argelia'],
            [31, 'Bolívar'],
            [31, 'Buenaventura'],
            [31, 'Buga'],
            [31, 'Bugalagrande'],
            [31, 'Caicedonia'],
            [31, 'Calima'],
            [31, 'Candelaria'],
            [31, 'Cartago'],
            [31, 'Dagua'],
            [31, 'El Águila'],
            [31, 'El Cairo'],
            [31, 'El Cerrito'],
            [31, 'El Dovio'],
            [31, 'Florida'],
            [31, 'Ginebra'],
            [31, 'Guacarí'],
            [31, 'Jamundí'],
            [31, 'La Cumbre'],
            [31, 'La Unión'],
            [31, 'La Victoria'],
            [31, 'Obando'],
            [31, 'Palmira'],
            [31, 'Pradera'],
            [31, 'Restrepo'],
            [31, 'Riofrío'],
            [31, 'Roldanillo'],
            [31, 'San Pedro'],
            [31, 'Sevilla'],
            [31, 'Toro'],
            [31, 'Trujillo'],
            [31, 'Tuluá'],
            [31, 'Ulloa'],
            [31, 'Versalles'],
            [31, 'Vijes'],
            [31, 'Yotoco'],
            [31, 'Yumbo'],
            [31, 'Zarzal'],

            // ── 32. Vaupés ───────────────────────────────
            [32, 'Mitú'],
            [32, 'Carurú'],
            [32, 'Pacoa'],
            [32, 'Papunaua'],
            [32, 'Taraira'],
            [32, 'Yavaraté'],

            // ── 33. Vichada ──────────────────────────────
            [33, 'Puerto Carreño'],
            [33, 'Cumaribo'],
            [33, 'La Primavera'],
            [33, 'Santa Rosalía'],
        ];

        // Insertar en chunks para no sobrecargar la memoria
        $rows = array_map(
            fn($m) => ['departamento_id' => $m[0], 'nombre' => $m[1]],
            $municipios
        );

        foreach (array_chunk($rows, 100) as $chunk) {
            DB::table('municipio')->insert($chunk);
        }
    }
}
